### ISSUE TITLE
Importing this library in the pad causes an error due to a test on line 135, but it works fine running it natively

### ISSUE THREAD

**Issue by marblecoma** [Omnikar/uiua-math#7]
I wanted to study your Day 20 AoC solution in the pad, but I get the error you can see in the screenshot from your math library import. If I run the same code from vs code, it works fine. 

This is the test on line 135:

  ⍤⤙≍ [¯2_3_0 ¯3_1_2] ⁅ QRot ¤:[3_2_0 1_3_2] RQuat η 0_0_1

Here is a link to the pad only containing the import: [Pad Link](https://www.uiua.org/pad?src=0_15_0-dev_1__IyBFeHBlcmltZW50YWwhCn4gImdpdDogZ2l0aHViLmNvbS9PbW5pa2FyL3VpdWEtbWF0aCIK)

![image](https://github.com/user-attachments/assets/d0580601-bb74-4967-beb2-70372e8adb36)

**Comment by Omnikar** [comment]
Looks like a failing test for quaternion rotation. I'll investigate this when I get the chance.

**Comment by Omnikar** [comment]
Looks like the [change to negative stack signature `repeat`](https://github.com/uiua-lang/uiua/commit/a635f8f5c265c0708165805ce1d7dc3eaeefd725) broke the `⍥₂Qqp` in the `QRot` implementation. The fix was just to change that to `Qqp Qqp`.
